### ISSUE TITLE
Install is failing :(

### ISSUE THREAD

**Issue by seeshabu** [kdw2060/hassio-addons#1]
Failed to install add-on
The command '/bin/ash -o pipefail -c apk add --no-cache nodejs-npm' returned a non-zero code: 1

**Comment by kdw2060** [comment]
Hey, sorry for the slow reply. I've only just started to work on add-ons again. Apparently there was some change of syntax necessary in the Dockerfile. Has been updated and install works again for the api-consumer and node starter project addons.
