### ISSUE TITLE
Add support for tasks? 

### ISSUE THREAD

**Issue by rr19-hub** [kdw2060/hassio-addons#14]
The addon is very helpful, thank you! Would there be the possibility to support tasks (caldav)? No errors are displayed in the log, but the data field remains empty. Would be great and should thereby probably also be suitable for Nextcloud.

**Comment by kdw2060** [comment]
Hi, good suggestion and this would certainly be doable, alas finding time is the issue here. I've got too many other projects going on in my spare time to delve into this. I'll keep it in mind, but don't expect to see anything soon.
