### ISSUE TITLE
Hass Calendar addon -> Error on start

### ISSUE THREAD

**Issue by Lawris** [kdw2060/hassio-addons#16]
Hello, thank you for developping this nice add-on, Home Assistant is definitely lacking the possibility to get more than 1 event from a calendar.

I did setup the addon following your guide and having this configuration:

```- calName: calendar_loris
  calType: google
  calId: *******@gmail.com
  googleServiceAccountKeyfile: home-assistant-mykey.json
```

Starting the add-on I always have the following log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
added 62 packages, and audited 63 packages in 14s
21 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
internal/fs/utils.js:332
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/data/allFutureEvents.json'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.<anonymous> (/index.js:378:30)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/data/allFutureEvents.json'
}
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Am I doing something wrong? Thanks for your help :)

**Comment by kdw2060** [comment]
Hi, odd that it fails on the non-existing data-backup for you. I just tested by removing the file on my own installation and that did not throw an error. I can make a change to the code to not fail on that step though, will make an update for that.

In the mean time, it also does look like your `calId` is not correct. This is not your google account e-mail adress but a specific unique id for a specific calendar. For me this id looks something like `stringofcharacters@group.calendar.google.com` Follow the link in the docs for information on how to retrieve this id.

**Comment by Lawris** [comment]
Hello, thanks a lot for your time, really appreciate it.

I followed the tutorial in the doc to setup your addon, apparently my id is also my e-mail address, maybe it works like that now?
<img width="1194" alt="Screenshot 2022-05-09 at 22 22 39" src="https://user-images.githubusercontent.com/15719068/167494157-66d5e8d8-807a-44de-a789-527f0c948a46.png">

I tried to create another calendar and, in fact, it gives me an id like yours. I replaced my `calId` with this new id and got another log output:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
added 62 packages, and audited 63 packages in 11s
21 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Previously stored events posted to sensor(s) at: Mon May 09 2022 22:39:30 GMT+0200 (Central European Summer Time)
postEventsAllCalendars error: TypeError: Cannot read property 'length' of undefined
```

So I did put back my original `calId` to verify if something changed and I keep getting the same logs for both `calId` now.

Could it be related to the json key file? Or permissions related to it?

**Comment by kdw2060** [comment]
Well, the good news is you don't get that ENOENT error anymore.
The new `TypeError: Cannot read property 'length' of undefined` error you see just means the calendar was empty for the queried period (check your config) or the request and the posting of the data just missing eachother in which case upon the next fetch the data should be there.

**Comment by Lawris** [comment]
You got it! I didn't share the calendar with the e-mail address of the service account. My bad for not reading the docs properly haha.

Now it works flawlessly, thank you for your patience.
Cheers.
