### ISSUE TITLE
error: sync caldav

### ISSUE THREAD

**Issue by mbuerki84** [kdw2060/hassio-addons#18]
Hello,

First of all, i would say thank you for this great addon.

Since I have updated to the newest version (0.201) I have sync problems with my caldav account (Synology Calendar). In version 0.200 everything works fine.
I use a synology NAS with the caldav calendar integration.

The following error message is shown in the log:
`CRON-Task: Events posted to sensor(s) at: Tue May 17 2022 06:11:23 GMT+0000 (Coordinated Universal Time) Calendar(s) queried at: Tue May 17 2022 06:12:23 GMT+0000 (Coordinated Universal Time) postEvents error with: Error: Request failed with status code 401 postEvents error with: Error: Request failed with status code 401`

Currently I have set the addon back to version 0.200 and everything works fine again. 
Maybe something is wrong with the update to 0.201?

Thank you for your help!

**Comment by kdw2060** [comment]
Something seems to have changed concerning how you obtain a supervisor_token to make api requests to the Home Assistant api. Can´t find a clue in the docs, nor github issues nor discord. Have asked a question in the dev-support channel on HA Discord, I hope a HA dev can point me in the right direction.

**Comment by kdw2060** [comment]
Found a solution, should work again when you update to 0.202
