### ISSUE TITLE
Addons can not load

### ISSUE THREAD

**Issue by zsamiatt** [kdw2060/hassio-addons#22]
Hello I use new home assistant.
 Home Assistant 2022.7.7 Supervisor 2022.07.0 Operating System 8.4 Kezelőfelület 20220707.1 - latest 

Error:
Failed to to call /store/repositories - Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules https://github.com/kdw2060/hassio-addon-calendar /data/addons/git/10a8315b stderr: 'Cloning into '/data/addons/git/10a8315b'... fatal: could not read Username for 'https://github.com': No such device or address '

**Comment by jensbab** [comment]
i face same issue. Does anybody has an idea?

**Comment by kdw2060** [comment]
hmm, not sure what is going wrong here. Sounds like maybe a config issue in Home Assistant itself that's not necessarily related to my addon-repo.

I'm currently working on an update and will add a 'My Home Assistant' button then too which will make it easier to install. Maybe you can try again then. Expect the update to arrive somewhere in september.
