### ISSUE TITLE
installes the addon...

### ISSUE THREAD

**Issue by jensbab** [kdw2060/hassio-addons#23]
Hi, just installed the addon. But now. What is the next step to get the calendar? There is a script in you description. is this needed? Where to put it?

**Comment by kdw2060** [comment]
If the installation and configuration are ok, then you should see a sensor with your calendar data under developer tools > states.

Next it's up to you to use that data in a card of your choice. If you never worked with home assistant's templating syntax or with json data in javascript, then that might be daunting and will take some time to learn. In my readme I link to the documentation for the templating syntax and there is one example string in the readme too.

You can play around with template strings under developer tools > template before using them i a card.
Example:
![Developer-Tools-–-Home-Assistant](https://user-images.githubusercontent.com/15030611/183743753-80ff5834-e5a1-4a79-84b7-35ebf08eb918.png)

The simplest card to experiment with is the markdown card. The most versatile card to use is the 'custom button card', the card-examples in my repo are of that type. Those examples also don't use the templating syntax from Home Assistant but regular javascript.
