### ISSUE TITLE
Today Only

### ISSUE THREAD

**Issue by tempus2016** [kdw2060/hassio-addons#25]
Is there a way to fetch only the calendar data for today and not for 1 day?  Looks like 1 day in the settings is the equivalent of 24 hours.  I'd like to only fetch and use the events for that specific day.

**Comment by kdw2060** [comment]
I think the best way to achieve this is in the presentation layer and doesn´t warrant a change on the add-on side. Just write a jinja template or some javascript inside the card that you use to display the events for today.

**Comment by tempus2016** [comment]
How would I go about getting only the events for today using jinja etc? I am only needing the start time for the first event of the day and the end time of the last event.

**Comment by kdw2060** [comment]
For templating/jinja, see [the Home Assistant docs](https://www.home-assistant.io/docs/configuration/templating/) and scour the Home Assistant forums for more examples. You should write logic in there where you compare the day of the event with today's date (check out the date/time examples on that HA doc page). Personally I find the Jinja templating syntax unintuitive and don't like to work with it, so I write javascript inside a custom button card instead. 
In both cases this will be somewhat daunting and take a lot of experimenting if you have no prior knowledge of scripting.
