### ISSUE TITLE
End dates are a day behind

### ISSUE THREAD

**Issue by tempus2016** [kdw2060/hassio-addons#26]
End dates show as the day before the start date. Am i missing something or is this a bug? 

<img width="371" alt="C8AD68F2-CB0E-4C42-A2C2-58195A885889" src="https://user-images.githubusercontent.com/40920327/192880037-2ad361ea-6adc-4d76-be33-844ceae231cd.png">

**Comment by kdw2060** [comment]
This is a bug indeed that sometimes appears. I'm working on a solution for the next release. No ETA for that I'm afraid, it'll be done when I have found the time to work on it.

**Comment by tempus2016** [comment]
> This is a bug indeed that sometimes appears. I'm working on a solution for the next release. No ETA for that I'm afraid, it'll be done when I have found the time to work on it.

Is there anything I can do in the mean time? I need to use the dates to work out what is today and what is not.

**Comment by kdw2060** [comment]
Are the separate `start_day` and `end_day` parameters not correct by any chance? If they are consistently wrong the same way you could add or subtract one day in a script. Bit of a stupid workaround, but the only thing you could do now.
It's a bug introduced by one of the libraries I'm using to parse the dates. I'm gonna switch over to a new library and run some extra tests on the date-parsing for different time-zones.
