### ISSUE TITLE
Incorrect start date

### ISSUE THREAD

**Issue by EagleStClair** [kdw2060/hassio-addons#27]
I have this setup for a icloud calendar but I noticed that the start date seems to add 1 day:
```
data: 
- endDate: '2022-10-10T18:00:00.000Z'
  startDate: '2022-10-11T16:00:00.000Z'
```
The event above goes from 16:00 to 18:00 on 2022-10-10, not start the day after it ends.

**Comment by kdw2060** [comment]
It is indeed a bug that sometimes appears, also see #26 
Like I said there, working on a fix, but I have no ETA for that, at the moment looks like I'll have some days of at the start of november when I should have time to code.

**Comment by kdw2060** [comment]
Please try the new version 0.300. In my test cases this issue has been fixed now. If you still experience this, then please reopen this issue and provide one or more ics files that give these incorrect dates.
