### ISSUE TITLE
postEventsAllCalendars error: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Timmwardion** [kdw2060/hassio-addons#29]
Hi There. I've spent a few hours on this and despite reading the other issues logs - I'm not getting anywhere.

Trying to sync with Google Calendar and keep getting the above error message. Tips that seem to have helped others aren't working in this case:
- Service account has been email given permission for the calendar
- Google Calendar API has been enabled
- calId is set correctly
- googleServiceAccountKeyfile confirmed to be in /share and spelled correctly

A previous comment said that this error just means that the calendar is empty for the date range queried but that isn't the case.

I'm out of ideas. It would be great if there was a verbose logging mode that could let me know how many calendars/events/etc were being returned and whether data was being written etc.

On looking at the code in index.js it seems like the issue may be when let numberOfEvents = events[`${sensorName}`].length; is called in line 346 which I assume might mean there is an issue with the allFutureEvents.json (which seems to not be being written). I'm a bit of a noob when it comes to home assistant though so that could be well wrong. FWIW here is my config

locale: en-gb
fetchDays: 365
fetchCRON: "*/30 * * * *"
calendarList:
  - calName: planner
    calType: google
    calId: email@email
    googleServiceAccountKeyfile: filename

**Comment by kdw2060** [comment]
Your debugging is probably correct, this may happen on the first run of the calendar-fetching when the timing is off between the reading/writing of the data. Normally if you just wait until the next fetch-run the error should disappear and your data should be there.

**Comment by Timmwardion** [comment]
Thanks - finally got it working and it seems to be pulling data. It would be great if the date range for that data pull was more flexible (365 days in the past AND future) to allow some better navigation, But that’s a separate issue. 

Currently I’m having some issues replicating your calendar samples as it seems the styles aren’t being applied at all. Can you tell me - is the custom: button-card used the standard button-card or something else. I get the logic of those scripts but it seems that the way styles are applied has changed since they were written (they work in raw HTML).

**Comment by kdw2060** [comment]
The custom button card is this one: https://github.com/custom-cards/button-card  (can be installed via hacs).
For the styling you need to have card mod installed: https://github.com/thomasloven/lovelace-card-mod (also installable via hacs)
