### ISSUE TITLE
wrong sort order of entity.state

### ISSUE THREAD

**Issue by ufgum** [kdw2060/hassio-addons#31]
I used the "onePersonNext4.yaml" card example and figured out, there is a wrong sort order. And the entry change some time just random, but he sync log shows all times the same order.

Using netxtcloud calender.

In the onePersonNext Card:
![2022-11-17_17-02](https://user-images.githubusercontent.com/1183243/202496681-9ccb37a2-5188-48ff-80e5-8a725689a5db.png)

sync log has every sync the same order:
![2022-11-17_17-08](https://user-images.githubusercontent.com/1183243/202497751-2c27856d-a885-4f5f-9981-25c73eb35b37.png)

I used the card from you're examples:

`type: custom:button-card
name: person-x
show_icon: false
show_name: false
entity: sensor.familien_kalender
custom_fields:
  person: '[[[ return `<img src="/media/local/moa.jpeg"/>` ]]]'
  calendar: |
    [[[ let calSnippet = '';
    //entity.state = sorted(entity.state);
    for (let i = 0; i < entity.state; i++) {
      if (i > 3) {};
      if (i <= 3 ) {
      let start_month = entity.attributes.data[i].startMonth;
      let start_day = entity.attributes.data[i].startDay;
      let start_time = entity.attributes.data[i].startTime;
      let end_month = entity.attributes.data[i].endMonth;
      let end_day = entity.attributes.data[i].endDay;
      let end_time = entity.attributes.data[i].endTime;
      let time = start_time;
      if (start_day !== end_day) {time = "Ganztägig"};
      if (end_day === start_day +1 && start_time === end_time) {time = "ganse dag"};
      let event = entity.attributes.data[i].summary;
      let location = entity.attributes.data[i].location;
      if (location === "" || location === undefined) {location = "-"}

    calSnippet += 
      `<table><tr>
          <td class="date month">${start_month}</td>
          <td class="event"><div class="event-title">${event}</div></td>
        </tr>
        <tr>
          <td class="date day">${start_day}</td>
          <td class="event"><span class="location"><ha-icon class="icon" icon="mdi:map-marker"></ha-icon>${location}</span><span class="time"><ha-icon class="icon" icon="mdi:clock-outline"></ha-icon>${time}</span></td>
        </tr></table>`
        }
    }
      
    return calSnippet; ]]]
styles:
  card:
    - color: rgba(0, 0, 0, 0.82)
    - margin-top: 1em
    - box-shadow: none
  grid:
    - grid-template-areas: '"person" "calendar"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content
  person:
    - align-self: middle
style: |
  img {
    border-radius: 50%;
    width: 120px;
    margin-bottom: 1em;
  }
  .icon {
    margin-right: 5%;
    text-align: center;
    float: left;
    width: 16px;
  }
  table {
    margin-left: 10px;
    box-sizing: border-box;
    border-spacing: 0;
    margin-bottom: 1.25em;
    width: 100%;
  }
  td {
    white-space: -o-pre-wrap; 
    word-wrap: break-word;
    white-space: pre-wrap; 
    white-space: -moz-pre-wrap; 
    white-space: -pre-wrap; 
  }
  .date {
    border-right: 2px solid #dc4225;
    width: 20%;
    text-align: center;
    color: #e1e1e1;
  }
  .event, .task {
    padding-left: 10px;
    width: 80%;
    color: #e1e1e1;
  }
  .month {
    text-transform: uppercase;
    vertical-align: bottom;
    color: #e1e1e1;
  }
  .day {
    font-size: 1.8em;
    vertical-align: top;
    color: #e1e1e1;
  }
  .event-title {
    margin-top: 0;
    font-size: 1.1em;
    font-weight: 400;
    text-align: left;
    font-family: 'SF UI Text Semibold';
    vertical-align: top;
    word-wrap: break-word;
    overflow-wrap: break-word;
    color: #e1e1e1;
  }
  .time, .location {
    display: block;
    text-align: left;
    font-size: 0.9em;
    padding-top: 5px;
    font-family: SF UI Text Regular;
    color: #e1e1e1;
  }
  .time {
    padding-bottom: 1em;
    color: #e1e1e1;
  }`

**Comment by kdw2060** [comment]
Yes, I had noticed the sorting error myself to. Have just posted an update that fixes this.
As usual you'll need to wait until the 2nd fetch run (based on your cron schedule) before you will see the change. (That is another small bug that still needs fixing).

**Comment by ufgum** [comment]
Thank you. The fix is working well. 
Another question, not wort to open issue: Is their a way to display the WeekDay as text in a crad? Like "Mo" "Th" "We"?

**Comment by kdw2060** [comment]
That weekday-notation would be quite easy to add. Just another format-option I can add with Luxon. I'll keep it in mind for a next update.
