### ISSUE TITLE
only reccurring birthday entries

### ISSUE THREAD

**Issue by nog-72** [kdw2060/hassio-addons#32]
Hi Kris,
first of all thanks for your great add-on, much appreciated!
Since the last update, however, I ran into a little issue. All birthday entries are not marked as recurring and are sorted at the top of the sensor so that even if I would like to see appointments of the next 4 days (fetchdays=4/fetchdayspast=0) based on your onePersonNext4.yaml I am only see birtday entries in a mixed order... similar issue were discribed by Ton in the home assistant community forum... However before the last update I was able to see appointments of the next four days so that I assume it is not an ics issue...
Pls. could you recheck update code or do you have any proposals to solve issue.
Thx.
KR
Nils

![grafik](https://user-images.githubusercontent.com/118939721/204617502-0f97df7b-35e4-4ff1-9676-3886c281ade0.png)

**Comment by kdw2060** [comment]
Hi Nils,

I use a couple of libraries to parse the ics files, I'd need a couple example ics files from you, so I can feed these through my test-parser to get an idea of what's going on here. You can upload them here.

If you can't do that, you could try creating a birthday entry in another software than you normally do and see if the issue occurs then too. For instance I use Thunderbird to make calendar entries (also birthdays) and don't have an issue with those. Different clients tend to have differences in their caldav implementation I noticed.

**Comment by nog-72** [comment]
Hi Kris,
You are right. I have created new recurring entry and birthday entry in SynologyCalendar and ACalender on my mobile. Both are sorted in the sensor in the right chronological order. So only old Entries imported from old windows calendar raised the issue. Now I am struggling to solve it with a batch....
Anyway, thx for you feedback which was very helpful.

**Comment by nog-72** [comment]
Closed.
