### ISSUE TITLE
Calendar entries over several days have no endate

### ISSUE THREAD

**Issue by mbuerki84** [kdw2060/hassio-addons#37]
Hello,

I have a problem with the Caldav calendar entries over several days.

When I create a entrie over multiple days for example: 15.12.2022 to 20.12.2022 with whole day = true the attributs (starttime enddate, enddateISO, endMonth, endMonthDigits, endday and endtime) from calendar entity report NULL.

My automation doesn't work with multiple calendar entries with whole day =true. I have a script with tts which tells me every morning the calendar entries today.

My system: 
HA Version 2022.11.5
OS: 9.3
Hass Calendar Addon: 0.301

With the Hass Calendar Addon version 0.202 it worked perfect.

Can anyone help?

Thank you!!
Mike

**Comment by kdw2060** [comment]
Hi Mike,

multiday events are not supported yet unfortunately. When I improved the handling of recurring events for v 0.300 I didn´t find the time to work on that aspect too. As you can see in the readme, it´s something that´s on my to do list for a future update.

If the previous version was working for you, you could download [this earlier commit](https://github.com/kdw2060/hassio-addons/tree/71f0d971e89f105804aa33c8fa1ca270a466dde7/hass-addon-calendar) here on github and add this to home assistant as a local addon. Info about locally installing an addon can be found on the home assistant developer documentation website.

**Comment by kdw2060** [comment]
This feature was added in the recent release (0.400)
