### ISSUE TITLE
ButtonCardJSTemplateError

### ISSUE THREAD

**Issue by Ofir-P** [kdw2060/hassio-addons#38]
Hey there kdw2060!
I'm trying to implement it to my dashboard and getting the following error:
`ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'state') in 'let calSnippet = ''; for (let i = 0; i < entity.state; i++) { if (i > 3) {}; if (i <= 3 ) { ...'`

Code I used to try:
https://pastebin.com/WXmvzmSU

**Comment by kdw2060** [comment]
Is your calendar entity really called `sensor.calendar.example` ? Seems like you didn't change the entity name to the one of your calendar. 
Also: if this was the first time you ran my add-on, wait a bit until the sensor gets populated. There's a bug where you need to wait for the second fetch run until it gets populated.

**Comment by Ofir-P** [comment]
> 



> Is your calendar entity really called `sensor.calendar.example` ? Seems like you didn't change the entity name to the one of your calendar. Also: if this was the first time you ran my add-on, wait a bit until the sensor gets populated. There's a bug where you need to wait for the second fetch run until it gets populated.

The calendar is in a diff name but the sensor does not exist, I have been waiting for 45 minutes since you posted to see if he gets populated.
also, I have checked in the state via Developer tools to see if he's there, and he's not even there.

**Comment by kdw2060** [comment]
ok, so your issue is not with the button card code but with the add-on not giving you a sensor. That was not clear from your problem description.
You have not posted your add-on config or add-on logs. I'll need those to make a guess about what's the issue.

**Comment by Ofir-P** [comment]
> ok, so your issue is not with the button card code but with the add-on not giving you a sensor. That was not clear from your problem description. You have not posted your add-on config or add-on logs. I'll need those to make a guess about what's the issue.

Hi sorry about that,
Here is the code editor version of the add-on configuration:
![image](https://user-images.githubusercontent.com/79255941/211204711-e1010c04-fb4c-418c-93a4-bc25a287ac8f.png)

and yaml:
`locale: he-IL
timeZone: ""
fetchDays: 5
fetchDaysPast: 0
fetchCRON: "*/30 * * * *"
calendarList:
  - calName: Ofir Calendar
    calType: google
    calId: xxx@gmail.com
    googleServiceAccountKeyfile: homeassistantxxx.json
`

Thanks for helping me!

**Comment by kdw2060** [comment]
I don't think a sensor name can contain spaces, hence the `calName` shouldn't either (should add that to the documentation). Change it to `Ofir_Calendar`.

And the calId is not your gmail email-address if that is what you have blurred out. [Check this information](https://docs.simplecalendar.io/find-google-calendar-id/) that I also link to in the docs.

**Comment by Ofir-P** [comment]
> I don't think a sensor name can contain spaces, hence the `calName` shouldn't either (should add that to the documentation). Change it to `Ofir_Calendar`.
> 
> And the calId is not your gmail email-address if that is what you have blurred out. [Check this information](https://docs.simplecalendar.io/find-google-calendar-id/) that I also link to in the docs.

Hey, thanks for the quick reply!
Well I followed the link you sent me (before I contact you) and by the ID field was my email address 
![image](https://user-images.githubusercontent.com/79255941/211208552-39ffcb83-4cdb-49f2-8d23-0fa4e7776eb6.png)

I will change anyway the calName field to 'Ofir' only.

**Comment by Ofir-P** [comment]
> I don't think a sensor name can contain spaces, hence the `calName` shouldn't either (should add that to the documentation). Change it to `Ofir_Calendar`.
> 
> And the calId is not your gmail email-address if that is what you have blurred out. [Check this information](https://docs.simplecalendar.io/find-google-calendar-id/) that I also link to in the docs.

Okay, my other calendars have a diff ID not only my email address as ID, so I tried one of them to check if the addon works.
by looking at the logs it seems that it can't find the .json file so it won't create any sensor.

Path to the .json file:
https://imgur.com/a7P4VKz
Logs:
http://pastie.org/p/5CTKWsUMvbqAYzE5PjyFjL
Configuration to the add-on:
http://pastie.org/p/5kFwswcxwiNhGprOvwm3eY

What did I do wrong? because it's on the right path.
Thanks for helping!

**Comment by kdw2060** [comment]
That path does not look right. Easiest is to use the samba add-on, then browse to the network folders in your file explorer and copy the json file to the /share folder that you should see as a network folder.

I saw your post on the HA forum, so guess you figured this out already, closing this issue.
