### ISSUE TITLE
Error 405 when connecting to Nextcloud caldav

### ISSUE THREAD

**Issue by ami6de** [kdw2060/hassio-addons#39]
Hello, I am experiencing an error 405 when trying to connect to a Nextcloud calDav instance:

ˋˋˋ
Calendar(s) queried at: Sun Jan 08 2023 22:54:00 GMT+0100 (Central European Standard Time)
postEventsAllCalendars error: TypeError: Cannot read properties of undefined (reading 'length')
Events posted to sensor(s) at: Sun Jan 08 2023 22:54:00 GMT+0100 (Central European Standard Time)
axios error: [object Object]Request failed with status code 405
ˋˋˋ

On Nextcloud, I do have a user which holds about 10 different calendars (family, school etc.). I tried changging the URL from
https://my.nexcloud.url/address/ 
To
https://my.nextcloud.url/address/remot.php/dav/
as suggested by NC and then got an error 415 instead.

Since it is not one but 10 calendars, would there be a requirement to specify one of these calendars by its name (e.g. 'family'), or will they all end up in one set of sensors?

**Comment by kdw2060** [comment]
You will need to make an entry in the `calendarList` of the add-on config for eacht seperate calendar you wish to include.
As for the url I found this post on NextClouds' help forum: https://help.nextcloud.com/t/how-to-connect-to-caldav-server/32981/3 
If that doesn't work I suggest you search further on that forum. I do not use NextCloud myself so I don't know its inner workings.
