### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/data/allFutureEvents.json'

### ISSUE THREAD

**Issue by gekberlin** [kdw2060/hassio-addons#41]
I do get the follwing error message when I start the addon:
> 6-rc: info: service s6rc-oneshot-runner: starting
> 
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> cont-init: info: running /etc/cont-init.d/00-banner.sh
> -----------------------------------------------------------
>  Add-on: Hass Calendar Addon
>  Addon to consume caldav and google calendars and make calendar events available as sensordata in Home Assistant.
> -----------------------------------------------------------
>  Add-on version: 0.301
>  You are running the latest version of this add-on.
>  System: null  (amd64 / qemux86-64)
>  Home Assistant Core: 2023.1.1
>  Home Assistant Supervisor: 2022.12.1
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
> cont-init: info: running /etc/cont-init.d/01-log-level.sh
> cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> added 80 packages, and audited 81 packages in 9s
> 23 packages are looking for funding
>   run `npm fund` for details
> found 0 vulnerabilities
> npm notice 
> npm notice New minor version of npm available! 9.1.2 -> 9.3.1
> npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.3.1>
> npm notice Run `npm install -g npm@9.3.1` to update!
> npm notice 
> System locale: en-US
> Luxon locale set to: de
> System timeZone: Europe/Berlin
> node:internal/fs/utils:347
>     throw err;
>     ^
> Error: ENOENT: no such file or directory, open '/data/allFutureEvents.json'
>     at Object.openSync (node:fs:590:3)
>     at Object.readFileSync (node:fs:458:35)
>     at Object.<anonymous> (/index.js:509:30)
>     at Module._compile (node:internal/modules/cjs/loader:1165:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
>     at Module.load (node:internal/modules/cjs/loader:1043:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:22:47 {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: '/data/allFutureEvents.json'
> }
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

My configuration is:

> locale: de
> timeZone: ""
> fetchDays: 40
> fetchDaysPast: 0
> fetchCRON: "*/30 * * * *"
> calendarList:
>   - calName: calendar_work
>     calType: google
>     calId: 3ln****_********7jrf8@group.calendar.google.com
>     googleServiceAccountKeyfile: home******_*******f40b2c0.json

**Comment by kdw2060** [comment]
looks like a mistake inside my code. I will fix in a next update.
For now, if you just change something in the options like the number of days to fetch or the CRON schedule and restart the addon then you will not get this error anymore. You will have to wait until the second fetch run until the data/sensor is there.

Leaving this ticket open for other users that might encounter the same issue, until I find time to fix it.

**Comment by kdw2060** [comment]
This bug has been fixed in the recent release (0.400)
