### ISSUE TITLE
Synology caldav - Request failed with status code 403

### ISSUE THREAD

**Issue by Mika255** [kdw2060/hassio-addons#42]
Hi, i'm having having a very similar problem as written in the setup guide, but even tough i'm waiting for several retries, it doesn't seem to initiate my caldav calendar: It's not creating an entity called "calendar-mika". I'm getting the following error:

```
Calendar(s) queried at: Sat Jan 21 2023 16:30:00 GMT+0100 (Central European Standard Time)
postEventsAllCalendars error: TypeError: Cannot read properties of undefined (reading 'length')
Events posted to sensor(s) at: Sat Jan 21 2023 16:30:00 GMT+0100 (Central European Standard Time)
axios error: [object Object]Request failed with status code 403
```

My caldav calendar works as default home assistant calendar.

I've check this problem, but seems just waiting solved it here:
https://github.com/kdw2060/hassio-addons/issues/29

**My setup**
Home Assistant 2023.1.6
Supervisor 2022.12.1
Frontend 20230110.0 - latest
It's running inside a docker container of my Synology 720+

**Here is my config**
```
locale: de
timeZone: Europe/Berlin
fetchDays: 365
fetchDaysPast: -7
fetchCRON: "*/30 * * * *"
calendarList:
  - calName: calendar-mika
    calType: caldav
    username: XXXX
    password: YYYY
    caldavUrl: http://192.168.1.75:8000/caldav.php/Mika/
```

**Here are the logs of this add-on:**

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh

-----------------------------------------------------------
 Add-on: Hass Calendar Addon
 Addon to consume caldav and google calendars and make calendar events available as sensordata in Home Assistant.
-----------------------------------------------------------
 Add-on version: 0.301
 You are running the latest version of this add-on.
 System: null  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.6
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

added 80 packages, and audited 81 packages in 8s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.1.2 -> 9.3.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.3.1>
npm notice Run `npm install -g npm@9.3.1` to update!
npm notice 
System locale: en-US
Luxon locale set to: de
System timeZone: Europe/Berlin
Luxon timezone set to: Europe/Berlin
Calendar(s) queried at: Sat Jan 21 2023 16:30:00 GMT+0100 (Central European Standard Time)
postEventsAllCalendars error: TypeError: Cannot read properties of undefined (reading 'length')
Events posted to sensor(s) at: Sat Jan 21 2023 16:30:00 GMT+0100 (Central European Standard Time)
axios error: [object Object]Request failed with status code 403
```

**Comment by kdw2060** [comment]
http error code 403 means 'forbidden'. It's a message from your caldav-server on your Synology. Most likely the username/password you're using are incorrect. Or that user does not have the rights to access the calendar this way.

**Comment by Mika255** [comment]
That's what i've suspected but the exact same Username/Password/URL combination works with the normal home assistant calendar integration. Is there a way to get more debug logs?

**Comment by Mika255** [comment]
Just found your answers in some other bugs about POSTMAN and tried this out.
Now I see that the 403 message is "The calendar-query report must be run against a calendar or a scheduling collection" 

<img width="897" alt="Screenshot 2023-01-21 at 20 38 59" src="https://user-images.githubusercontent.com/67970450/213884250-f0943a07-788d-4138-bee3-8a518c64f49e.png">

**Comment by kdw2060** [comment]
Yeah, I was going to suggest you use Postman.
I am not familiar with whatever Caldav-server you are running, but guessing from this error message I think you need to add a calendar-name after the /Mika/ in your url.

**Comment by Mika255** [comment]
Amazing, its working now! Synology is adding "home" to the path. Somehow the normal home-assisant caldav integration is adding "home" automatically it seems.

Thanks for your help!

<img width="703" alt="Screenshot 2023-01-22 at 00 21 45" src="https://user-images.githubusercontent.com/67970450/213893885-09c19c3b-79f2-45dd-a2f9-099d37a972b3.png">

**Comment by tempus2016** [comment]
How do you run this in docker?  I have no idea where to start
