### ISSUE TITLE
postEventsAllCalendars error: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Timmwardion** [kdw2060/hassio-addons#46]
I'm getting what seems to be an intermittent error.

postEventsAllCalendars error: TypeError: Cannot read properties of undefined (reading 'length')

Which seemingly causes all HASS Calendar data to be unavailable - i.e. the cards using that data go blank.

Add-On log shows the error above, supervisor log shows (not very helpful):

WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Hass Calendar Addon is failed, restarting...

I'm assuming that one of the calendars has no events on one of the days - but it feels like the add-on should be more robust than that.

Using both Gmail and Caldav calendars

**Comment by kdw2060** [comment]
It shouldn't crash on an empty calendar indeed. I'll add a check on empty calendars in a next release.

**Comment by kdw2060** [comment]
This bug has been fixed in the recent release (0.400)
