### ISSUE TITLE
add originalYear to available values

### ISSUE THREAD

**Issue by nicedevil007** [kdw2060/hassio-addons#47]
Hi I'm trying to setup your addon with an Alexa notification that tells me each day if there is a birthday in my calendar, if so it will tell me the entry's summary and then calucaltes the age of that person.

This should ofc only work if the year of birth is known.

Maybe you can add the originalYear that makes the past calculation a lot easier then? :)

That is what I have done right now:

```
{{state_attr('sensor.geburtstage', 'data')[0].summary}} Alter:
{{now().strftime('%Y') | int - state_attr('sensor.geburtstage',
'data')[0].originalStartDate[:4] | int}}
```

**Comment by kdw2060** [comment]
This feature was added in the recent release (0.400)
