### ISSUE TITLE
Error 404 while fetching events from Nextcloud

### ISSUE THREAD

**Issue by alsvartr** [kdw2060/hassio-addons#48]
Hello, I'm trying to setup new caldav calendar stored in nextcloud and got this error:
`error with: Error: Request failed with status code 404[object Object]`

This what I got in nextcloud logs:
`"GET /remote.php/dav/calendars/alsvartr/test/c167f8df-a884-463c-9217-e5f41288608b.ics HTTP/1.0" 404 248 "-" "axios/0.24.0" `

This is a "subscription" calendar in nextcloud and I assume this is a cause. But other caldav clients works fine, including HA caldav integration.

**Comment by kdw2060** [comment]
I'm not sure my add-on will work with that kind of subscription calendars indeed. Have not tested that, nor is there specific code to handle possible differences with 'normal' calendars.

That said, the 404 makes me think the url you configured might be wrong. Did you use `{yourNextclouddomain}/remote.php/dav/calendars/alsvartr/test/c167f8df-a884-463c-9217-e5f41288608b.ics` in the add-on config? That will certainly not work.
`{yourNextclouddomain}/remote.php/dav/calendars/alsvartr/test/` or `{yourNextclouddomain}/remote.php/dav/calendars/alsvartr/` might.

**Comment by alsvartr** [comment]
No, this is my add-on config:
```
- calName: test
  calType: caldav
  username: alsvartr
  password: 
  caldavUrl: >-
    https://domain/remote.php/dav/calendars/alsvartr/test/
```

I don't know exactly how caldav works and might be wrong, but I don't see requests to any ics files from other tools (DAVx5 or Evolution for example). Which makes me think that your add-on works with caldav differently through retrieveing specific events via GET requests and that might not work with subscription calendars.

**Comment by kdw2060** [comment]
Yes, it does make a GET request for every single event, still I think it's odd this would result in a 404 as the `c167f8df-a884-463c-9217-e5f41288608b.ics` comes from the response of your Nextcloud server to the earlier report query.
I'd expect my add-on to fail on the parsing of the ics file, not earlier on the GET as it seems to do.

I do have plans to set up my own NextCloud/Owncloud instance in the future, I'll probably work on improving compatibility then. Closing this issue for now.
