### ISSUE TITLE
Failed to restart Hass Calendar Addon

### ISSUE THREAD

**Issue by AbuEesa** [kdw2060/hassio-addons#49]
Hi,
thanks the addonn I am trying to make it work, running it for the first time trying to fetch claendar data from synology using Caldav 

I have tried a new calendar with couple of test events in there.

`
Failed to restart Hass Calendar Addon
Can't create container from addon_6a4ec433_hass_calendar_addon: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_6a4ec433_hass_calendar_addon: Conflict ("Conflict. The container name "/addon_6a4ec433_hass_calendar_addon" is already in use by container "0457bff207494b354f1ab1ae94574e36ffa658bd483734f2996744be01c0530a". You have to remove (or rename) that container to be able to reuse that name.")
`

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
parse error: Expected string key before ':' at line 1, column 4
[10:56:12] ERROR: Unknown HTTP error occured
 Add-on: 
 
-----------------------------------------------------------
 Add-on version: 
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[10:56:12] ERROR: Unknown HTTP error occured
 System:   ( / )
 Home Assistant Core: 
 Home Assistant Supervisor: 
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------`

Please advie?

**Comment by kdw2060** [comment]
Sounds like a docker issue. Try stop > rebuild > restart 
If that doesn't work you could stop the addon, then use portainer or the docker cli to delete the mentioned container , then again rebuild and restart.

I'm no docker expert, but I guess that should fix the issue.

**Comment by AbuEesa** [comment]
thanks for your help on this, I manged to fix it :)

Now logs are not giving me any error but no calendar entries are imported either and of course no sensor if created, 
I am using synology and reading through a closed issue I am using correct url (with trailing slash) my config and logs are as follows

`locale: en-gb
timeZone: Australia/Perth
fetchDays: 10
fetchDaysPast: 0
fetchCRON: "*/30 * * * *"
calendarList:
  - calName: Syno Calendar
    calType: caldav
    username: haSidhu
    password: 6908215A2B26156F9371DE3C59680C02
    caldavUrl: https://rs.******.com/caldav/ha****/home/
  - calName: Syno Family Calendar
    calType: caldav
    username: "!secret synouser"
    password: "!secret synopass"
    caldavUrl: https://rs.si*****.com/caldav/ha***/zlndz/`

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Hass Calendar Addon
 Addon to consume caldav and google calendars and make calendar events available as sensordata in Home Assistant.
-----------------------------------------------------------
 Add-on version: 0.301
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.4.4
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
added 80 packages, and audited 81 packages in 12s
23 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.1.2 -> 9.6.4
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.4>
npm notice Run `npm install -g npm@9.6.4` to update!
npm notice 
System locale: en-US
Luxon locale set to: en-gb
System timeZone: Australia/Perth
Luxon timezone set to: Australia/Perth
no previously stored options found`

**Comment by AbuEesa** [comment]
ok I am getting this now, after remving trailing slash from the url, now its fetching the entries but there are portEvent errors.

Calendar(s) queried at: Sun Apr 16 2023 05:00:00 GMT+0800 (Australian Western Standard Time)
**postEvents error with: Error: Request failed with status code 500
postEvents error with: Error: Request failed with status code 500**
Events posted to sensor(s) at: Sun Apr 16 2023 05:00:01 GMT+0800 (Australian Western Standard Time)
3 entries found in caldav calendar
Fetching caldav calendar entry 20230415T102938-d58a122f%40192.168.20.25.ics
Fetching caldav calendar entry 20230415T102943-4e783bdb%40192.168.20.25.ics
Fetching caldav calendar entry 20230415T141138-858f37f5%40192.168.20.25.ics
10 entries found in caldav calendar
Fetching caldav calendar entry D6C640C6-477B-4272-97C7-A36C9C2AD52E.ics
Fetching caldav calendar entry 42A0DB8C-83E6-43A2-9ED2-C595C5D81A7E.ics
Fetching caldav calendar entry CC2A7429-6EA0-4251-873C-ABB78AD35309.ics
Fetching caldav calendar entry 716576B1-2326-41E4-8A6C-71C60AE4E75D.ics
Fetching caldav calendar entry 3E2A7FB2-194C-454D-BAB9-EE9751F2A49C.ics
Fetching caldav calendar entry 11A70671-1002-421B-AF05-78D24DDE99A1.ics
Fetching caldav calendar entry F13C6B43-1AB9-4BB1-A9C7-2B15AA45F5B9.ics
Fetching caldav calendar entry 20221219T160729-4457690b%40192.168.20.25.ics
Fetching caldav calendar entry 20220819T093349-2357c2e8%40192.168.20.25.ics
Fetching caldav calendar entry 20220819T092906-26245ace%40192.168.20.25.ics
sorting events of calendar: Syno Calender
sorting events of calendar: Fam Syno Calender
