### ISSUE TITLE
fetch days past for specific calendar in the calendarlist

### ISSUE THREAD

**Issue by mbuerki84** [kdw2060/hassio-addons#53]
Hello,

Is it possible to add the function "fetchDaysPast" for specific calendar not for all calendar in the calendarlist?
see the example below.

locale: de-ch
timeZone: ""
fetchDays: 365
fetchCRON: "*/30 * * * *"
calendarList:
  - calName: calendar_1
    fetchDaysPast: -365
    calType: caldav
    username: ""
    password: ""
    caldavUrl: ""
  - calName: calendar_2
    fetchDaysPast: 0
    calType: caldav
    username: ""
    password: ""
    caldavUrl: ""

Thank you for the answer.

Mike

**Comment by kdw2060** [comment]
hi Mike, I'll consider it when I start working on the next update. However, the same result could also be achieved by filtering the calendar-data in your jinja or javascript templates that you need to write anyway to display the data in a card.

**Comment by kdw2060** [comment]
Decided not to implement this feature request as it can be achieved in the front-end already.
