### ISSUE TITLE
Home Assistant: Write Calender content to an Sensor

### ISSUE THREAD

**Issue by Uli1900** [kdw2060/hassio-addons#54]
Hello, I need help: I want to write calender appointments (internal HA Calender) to an sensor for today, for tomorrow, and for tomorrow +1

Can somebody help me?

Thanks a lot!

**Comment by kdw2060** [comment]
That sounds like a question you should post on the HA forums and not here as you state you're using the internal HA calendar. What you want can probably be done by creating [template sensors](https://www.home-assistant.io/integrations/template/)
