### ISSUE TITLE
How to show current event (today) and upcoming (tomorrow)?

### ISSUE THREAD

**Issue by hAMMERlized** [kdw2060/hassio-addons#57]
Hey,

first of all, thanks to this great addon! Maybe i am just too stupid but how do i show only the current event(s) from today and just the upcoming from, let's say, tomorrow and maybe the day after tomorrow?

Only way i can achieve this is to set `fetchDaysPast` to -1 and `fetchDays` to 1. But then it shows the event from yesterday, which is not what i want. I want just to display today and tomorrow (maybe the day after tomorrow too).

Thanks

**Comment by kdw2060** [comment]
`fetchDaysPast` is optional, just leave that out of the config.
`fetchDays = 1`  should equal today and tomorrow
