### ISSUE TITLE
Date's include time

### ISSUE THREAD

**Issue by tempus2016** [kdw2060/hassio-addons#60]
Is there a way to remove the time from startDate and endDate?  For some reason, the is a comma then the time after the date.  The date attribute should show the date only.

<img width="543" alt="Screenshot 2024-10-16 at 01 43 17" src="https://github.com/user-attachments/assets/61fc1936-4b72-427d-9597-c598f1fdabd3">

While looking, I also noticed the month shows 'okt' instead of 'oct'.  How can I fix this?

**Comment by kdw2060** [comment]
Hi, the startDate and startDateISO are deliberately dateTime-objects and I'm going to keep this like that. You can calculate/manipulate various date-presentations or date-differences from them.

You could either use a [home-assistant jinja template](https://www.home-assistant.io/docs/configuration/templating/) to render the dateTime in the manner you prefer or combine the various seperate elements (year, day, ...) from the sensor.

As for the okt/oct spelling, this is determined by the locale you set in the addon configuration. Change this to your preferred locale and it will show the month abbreviation in the language associated with that locale.
