### ISSUE TITLE
[Question] decrease pulliing calendar pulls

### ISSUE THREAD

**Issue by thundergreen** [kdw2060/hassio-addons#9]
Could you please guide me how i can chage the pulling from 30 minutes to 60 seconds? Will fork this repo and use modified version then :) 

found:

```
// Getting and posting events every 30 minutes
cron.schedule("4,34 * * * *", () => {
  getEvents();
  console.log("Calendar(s) queried at: " + new Date());
});

cron.schedule("6,36 * * * *", () => {
  fs.writeFileSync("/data/allFutureEvents.json", JSON.stringify(allFutureEvents), (err) => {
    if (err) {
      console.log(err);
      return;
    }
  });
  postEventsAllCalendars();
  console.log("Events posted to sensor(s) at: " + new Date());
});
```
But how to change this to 60 seconds?

can this be right? :

```
// Getting and posting events every 30 minutes
cron.schedule("/1 * * * *", () => {
  getEvents();
  console.log("Calendar(s) queried at: " + new Date());
});

cron.schedule("/1 * * * *", () => {
  fs.writeFileSync("/data/allFutureEvents.json", JSON.stringify(allFutureEvents), (err) => {
    if (err) {
      console.log(err);
      return;
    }
  });
  postEventsAllCalendars();
  console.log("Events posted to sensor(s) at: " + new Date());
});
```

**Comment by kdw2060** [comment]
I noticed one of the people that forked my repo has already extended the addon config so you can enter a custom cron-schedule, and he also made the code better regarding the async nature of the calls. I was planning to include his improvements in a future version myself. In the meantime you could install his fork to get what you want: https://github.com/cellerich/hassio-addons/tree/master/hass-addon-calendar

In the addon-config then set the schedule.

**Comment by cellerich** [comment]
Hi, this was me.
I planned to make a branch and then do a Request to merge but I‘m not so fluent with GIT. Feel free to copy the code over!
I also added a version for Baikal specific API ( which I use)

Regards, Cello
Am 17. März 2022, 20:22 +0100 schrieb Kris De Winter ***@***.***>:
